// Copyright 2018 Peter Wild
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef DOCS_H
#define DOCS_H

#include <string>
#include <cstdint>

//#define SHORT_DOCS

namespace Docs
{
	const std::string version     { "1.0" };
	const std::string compiledate { static_cast<std::string>(__DATE__) };
	const std::string lastupdate  { "May 18 2018" }; // this is for the help text, not the program

	const std::string helptext    { "Type h for help, z for credits or select one of the following modes." };
	const std::string modes       { "Modes: beginner(b), novice(n), intermediate(i), advanced(a), expert(e), master(m), grandmaster(g), custom(c)" };
	const std::string helptitle   { "Minesweeper Help" };
	
	const std::string fill        {"================================================================================"};

	const std::string help[]
	{
#ifndef SHORT_DOCS
		"Minesweeper is a single player video game which has its origins in the mainframe",
		"games of the 1960s and 1970s. The aim of minesweeper is to clear a rectangular  ",
		"board containing mines without detonating any of them, with the help of squares ",
		"adjacent to mines, which denote the number of neighbouring mines in a 3 by 3    ",
		"arrangement. Squares are uncovered one at a time, with the coordinates of the   ",
		"square being entered in base-36 (numbers 0-9, followed by letters A-Z) with the ",
		"format (X,Y). If an uncovered square has zero adjacent mines, the square will be",
		"blank and all adjacent squares will be recursively revealed. The player loses if",
		"they uncover a square with a mine. When the game set up the board, a mine will  ",
		"never be placed on the first square uncovered. Flags can also be used to help   ",
		"with gameplay; they can be used by adding a symbol before the coordinate. Flags ",
		"cannot be used on the first turn. The current flags in the game are listed as   ",
		"follows:                                                                        ",
		"                                                                                ",
		"    !   Mark an uncovered square as containing a mine. The square can no longer ",
		"        be uncovered and the mines remaining counter will be decreased by 1.    ",
		"        If at the end a marked square is revealed to have been incorrectly      ",
		"        placed, it is replaced on the grid with the incorrect mark marker (:).  ",
		"                                                                                ",
		"    ?   Mark an uncovered square with a question mark. This serves as an aid to ",
		"        logical deduction, but does not prevent the square from being uncovered.",
		"                                                                                ",
		"    #   Return a previously marked square with an exclamation mark or question  ",
		"        mark to its unmarked state.                                             ",
		"                                                                                ",
		"    %   Uncover all unmarked tiles. This is a quick shortcut to use instead of  ",
		"        manually uncovering all of the remaining tiles. This flag should be used",
		"        only when you are certain that you have marked all squares with mines,  ",
		"        otherwise it may result in a loss. The coordinate given is redundant.   ",
		"                                                                                ",
		"    @   Surrender and reveal all squares. The coordinate given is redundant.    ",
		"                                                                                ",
		"                                                                                ",
		"                                                                                ",
		"At the start of the game, the player is presented with presets for mine boards. ",
		"Here is an explaination of the options:                                         ",
		"                                                                                ",
		"    b    Beginner: a 9 by 9 grid with 10 mines. This is the 'beginner' mode from",
		"         Microsoft Minesweeper from Windows 2000 onwards.                       ",
		"                                                                                ",
		"    n    Novice: an 8 by 8 grid with 10 mines. This was the original 'beginner' ",
		"         mode from Microsoft Win Mine, when it was first made in July 1990.     ",
		"                                                                                ",
		"    i    Intermediate: a 16 by 16 grid with 40 mines, which has been in the game",
		"         as 'intermediate' since Microsoft Minesweeper was first introduced.    ",
		"                                                                                ",
		"    a    Advanced: a 24 by 24 grid with 99 mines. This was the original 'expert'",
		"         mode in Win Mine, which was replaced by a 16 by 30 grid when Microsoft ",
		"         published Minesweeper as part of the Windows Entertainment Pack (1990).",
		"                                                                                ",
		"    e    Expert: a 16 by 30 grid with 99 mines. This mode appears in all of the ",
		"         published versions of Minesweeper (not including Win Mine).            ",
		"                                                                                ",
		"    m    Master: a 24 by 30 grid with 200 mines. 24 by 30 is the maximum size of",
		"         a custom board in Microsoft Minesweeper.                               ",
		"                                                                                ",
		"    g    Grandmaster: a 36 by 36 grid with 50% mine density (648 mines). This is",
		"         the maximum grid size possible in this implementation of Minesweeper   ",
		"         due to limitations in the current input method and the number of       ",
		"         characters in base-36. This is mode is extremely difficult. Good Luck. ",
		"                                                                                ",
		"    d    Debug: a 5 by 5 grid with 1 mine for testing purposes.                 ",
		"                                                                                ",
		"    c    Custom: see below:                                                     ",
		"                                                                                ",
		"Custom mode allows for a maximum board size of 36 by 36, with a minimum side    ",
		"length of 5. The size of board is entered in base-36 coordinate (0-Z). The      ",
		"number of mines can also be determined by the user, with the minimum number of  ",
		"mines being 1 and the maximum being the number of squares in the board - 1.     ",
		"                                                                                ",
		"                                                                                ",
		"Here is a good website for minesweeper strategy:                                ",
		"http://www.minesweeper.info/wiki/Strategy                                       "
#else
		"The help text can be found online at:                                           ",
		"https://github.com/wildp/console-minesweeper/blob/master/HELP.md                "
#endif
	};

	const std::string credits[]
	{
		"Console Minsweeper                                                              ",
		"Copyright 2018 Peter Wild                                                       ",
		"Licensed under the Apache License, Version 2.0                                  ",
		"                                                                                ",
		"The latest version of the source code can be found here:                        ",
		"https://github.com/wildp/console-minesweeper                                    ",
		"                                                                                ",
		"Sources for general background information in the help text:                    ",
		"https://en.wikipedia.org/wiki/Minesweeper_(video_game)                          ",
		"http://www.minesweeper.info/wiki/Windows_Minesweeper                            "
	};

#ifndef SHORT_DOCS
	const std::string licencetitle{ "Console Minesweeper is licensed under the Apache License, Version 2.0" };
#else
	const std::string licencetitle{ "License" };
#endif
	const std::string licence[]
	{
#ifndef SHORT_DOCS
		"                               Apache License                                   ",
		"                         Version 2.0, January 2004                              ",
		"                      http://www.apache.org/licenses/                           ",
		"                                                                                ",
		" TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION                   ",
		"                                                                                ",
		" 1. Definitions.                                                                ",
		"                                                                                ",
		"    \"License\" shall mean the terms and conditions for use, reproduction,      ",
		"    and distribution as defined by Sections 1 through 9 of this document.       ",
		"                                                                                ",
		"    \"Licensor\" shall mean the copyright owner or entity authorized by         ",
		"    the copyright owner that is granting the License.                           ",
		"                                                                                ",
		"    \"Legal Entity\" shall mean the union of the acting entity and all          ",
		"    other entities that control, are controlled by, or are under common         ",
		"    control with that entity. For the purposes of this definition,              ",
		"    \"control\" means (i) the power, direct or indirect, to cause the           ",
		"    direction or management of such entity, whether by contract or              ",
		"    otherwise, or (ii) ownership of fifty percent (50%) or more of the          ",
		"    outstanding shares, or (iii) beneficial ownership of such entity.           ",
		"                                                                                ",
		"    \"You\" (or \"Your\") shall mean an individual or Legal Entity              ",
		"    exercising permissions granted by this License.                             ",
		"                                                                                ",
		"    \"Source\" form shall mean the preferred form for making modifications,     ",
		"    including but not limited to software source code, documentation            ",
		"    source, and configuration files.                                            ",
		"                                                                                ",
		"    \"Object\" form shall mean any form resulting from mechanical               ",
		"    transformation or translation of a Source form, including but               ",
		"    not limited to compiled object code, generated documentation,               ",
		"    and conversions to other media types.                                       ",
		"                                                                                ",
		"    \"Work\" shall mean the work of authorship, whether in Source or            ",
		"    Object form, made available under the License, as indicated by a            ",
		"    copyright notice that is included in or attached to the work                ",
		"    (an example is provided in the Appendix below).                             ",
		"                                                                                ",
		"    \"Derivative Works\" shall mean any work, whether in Source or Object       ",
		"    form, that is based on (or derived from) the Work and for which the         ",
		"    editorial revisions, annotations, elaborations, or other modifications      ",
		"    represent, as a whole, an original work of authorship. For the purposes     ",
		"    of this License, Derivative Works shall not include works that remain       ",
		"    separable from, or merely link (or bind by name) to the interfaces of,      ",
		"    the Work and Derivative Works thereof.                                      ",
		"                                                                                ",
		"    \"Contribution\" shall mean any work of authorship, including               ",
		"    the original version of the Work and any modifications or additions         ",
		"    to that Work or Derivative Works thereof, that is intentionally             ",
		"    submitted to Licensor for inclusion in the Work by the copyright owner      ",
		"    or by an individual or Legal Entity authorized to submit on behalf of       ",
		"    the copyright owner. For the purposes of this definition, \"submitted\"     ",
		"    means any form of electronic, verbal, or written communication sent         ",
		"    to the Licensor or its representatives, including but not limited to        ",
		"    communication on electronic mailing lists, source code control systems,     ",
		"    and issue tracking systems that are managed by, or on behalf of, the        ",
		"    Licensor for the purpose of discussing and improving the Work, but          ",
		"    excluding communication that is conspicuously marked or otherwise           ",
		"    designated in writing by the copyright owner as \"Not a Contribution.\"     ",
		"                                                                                ",
		"    \"Contributor\" shall mean Licensor and any individual or Legal Entity      ",
		"    on behalf of whom a Contribution has been received by Licensor and          ",
		"    subsequently incorporated within the Work.                                  ",
		"                                                                                ",
		" 2. Grant of Copyright License. Subject to the terms and conditions of          ",
		"    this License, each Contributor hereby grants to You a perpetual,            ",
		"    worldwide, non-exclusive, no-charge, royalty-free, irrevocable              ",
		"    copyright license to reproduce, prepare Derivative Works of,                ",
		"    publicly display, publicly perform, sublicense, and distribute the          ",
		"    Work and such Derivative Works in Source or Object form.                    ",
		"                                                                                ",
		" 3. Grant of Patent License. Subject to the terms and conditions of             ",
		"    this License, each Contributor hereby grants to You a perpetual,            ",
		"    worldwide, non-exclusive, no-charge, royalty-free, irrevocable              ",
		"    (except as stated in this section) patent license to make, have made,       ",
		"    use, offer to sell, sell, import, and otherwise transfer the Work,          ",
		"    where such license applies only to those patent claims licensable           ",
		"    by such Contributor that are necessarily infringed by their                 ",
		"    Contribution(s) alone or by combination of their Contribution(s)            ",
		"    with the Work to which such Contribution(s) was submitted. If You           ",
		"    institute patent litigation against any entity (including a                 ",
		"    cross-claim or counterclaim in a lawsuit) alleging that the Work            ",
		"    or a Contribution incorporated within the Work constitutes direct           ",
		"    or contributory patent infringement, then any patent licenses               ",
		"    granted to You under this License for that Work shall terminate             ",
		"    as of the date such litigation is filed.                                    ",
		"                                                                                ",
		" 4. Redistribution. You may reproduce and distribute copies of the              ",
		"    Work or Derivative Works thereof in any medium, with or without             ",
		"    modifications, and in Source or Object form, provided that You              ",
		"    meet the following conditions:                                              ",
		"                                                                                ",
		"    (a) You must give any other recipients of the Work or                       ",
		"        Derivative Works a copy of this License; and                            ",
		"                                                                                ",
		"    (b) You must cause any modified files to carry prominent notices            ",
		"        stating that You changed the files; and                                 ",
		"                                                                                ",
		"    (c) You must retain, in the Source form of any Derivative Works             ",
		"        that You distribute, all copyright, patent, trademark, and              ",
		"        attribution notices from the Source form of the Work,                   ",
		"        excluding those notices that do not pertain to any part of              ",
		"        the Derivative Works; and                                               ",
		"                                                                                ",
		"    (d) If the Work includes a \"NOTICE\" text file as part of its              ",
		"        distribution, then any Derivative Works that You distribute must        ",
		"        include a readable copy of the attribution notices contained            ",
		"        within such NOTICE file, excluding those notices that do not            ",
		"        pertain to any part of the Derivative Works, in at least one            ",
		"        of the following places: within a NOTICE text file distributed          ",
		"        as part of the Derivative Works; within the Source form or              ",
		"        documentation, if provided along with the Derivative Works; or,         ",
		"        within a display generated by the Derivative Works, if and              ",
		"        wherever such third-party notices normally appear. The contents         ",
		"        of the NOTICE file are for informational purposes only and              ",
		"        do not modify the License. You may add Your own attribution             ",
		"        notices within Derivative Works that You distribute, alongside          ",
		"        or as an addendum to the NOTICE text from the Work, provided            ",
		"        that such additional attribution notices cannot be construed            ",
		"        as modifying the License.                                               ",
		"                                                                                ",
		"    You may add Your own copyright statement to Your modifications and          ",
		"    may provide additional or different license terms and conditions            ",
		"    for use, reproduction, or distribution of Your modifications, or            ",
		"    for any such Derivative Works as a whole, provided Your use,                ",
		"    reproduction, and distribution of the Work otherwise complies with          ",
		"    the conditions stated in this License.                                      ",
		"                                                                                ",
		" 5. Submission of Contributions. Unless You explicitly state otherwise,         ",
		"    any Contribution intentionally submitted for inclusion in the Work          ",
		"    by You to the Licensor shall be under the terms and conditions of           ",
		"    this License, without any additional terms or conditions.                   ",
		"    Notwithstanding the above, nothing herein shall supersede or modify         ",
		"    the terms of any separate license agreement you may have executed           ",
		"    with Licensor regarding such Contributions.                                 ",
		"                                                                                ",
		" 6. Trademarks. This License does not grant permission to use the trade         ",
		"    names, trademarks, service marks, or product names of the Licensor,         ",
		"    except as required for reasonable and customary use in describing the       ",
		"    origin of the Work and reproducing the content of the NOTICE file.          ",
		"                                                                                ",
		" 7. Disclaimer of Warranty. Unless required by applicable law or                ",
		"    agreed to in writing, Licensor provides the Work (and each                  ",
		"    Contributor provides its Contributions) on an \"AS IS\" BASIS,              ",
		"    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or             ",
		"    implied, including, without limitation, any warranties or conditions        ",
		"    of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A               ",
		"    PARTICULAR PURPOSE. You are solely responsible for determining the          ",
		"    appropriateness of using or redistributing the Work and assume any          ",
		"    risks associated with Your exercise of permissions under this License.      ",
		"                                                                                ",
		" 8. Limitation of Liability. In no event and under no legal theory,             ",
		"    whether in tort (including negligence), contract, or otherwise,             ",
		"    unless required by applicable law (such as deliberate and grossly           ",
		"    negligent acts) or agreed to in writing, shall any Contributor be           ",
		"    liable to You for damages, including any direct, indirect, special,         ",
		"    incidental, or consequential damages of any character arising as a          ",
		"    result of this License or out of the use or inability to use the            ",
		"    Work (including but not limited to damages for loss of goodwill,            ",
		"    work stoppage, computer failure or malfunction, or any and all              ",
		"    other commercial damages or losses), even if such Contributor               ",
		"    has been advised of the possibility of such damages.                        ",
		"                                                                                ",
		" 9. Accepting Warranty or Additional Liability. While redistributing            ",
		"    the Work or Derivative Works thereof, You may choose to offer,              ",
		"    and charge a fee for, acceptance of support, warranty, indemnity,           ",
		"    or other liability obligations and/or rights consistent with this           ",
		"    License. However, in accepting such obligations, You may act only           ",
		"    on Your own behalf and on Your sole responsibility, not on behalf           ",
		"    of any other Contributor, and only if You agree to indemnify,               ",
		"    defend, and hold each Contributor harmless for any liability                ",
		"    incurred by, or claims asserted against, such Contributor by reason         ",
		"    of your accepting any such warranty or additional liability.                ",
		"                                                                                ",
		" END OF TERMS AND CONDITIONS                                                    ",
		"                                                                                ",
		" APPENDIX: How to apply the Apache License to your work.                        ",
		"                                                                                ",
		"    To apply the Apache License to your work, attach the following              ",
		"    boilerplate notice, with the fields enclosed by brackets \"[]\"             ",
		"    replaced with your own identifying information. (Don't include              ",
		"    the brackets!)  The text should be enclosed in the appropriate              ",
		"    comment syntax for the file format. We also recommend that a                ",
		"    file or class name and description of purpose be included on the            ",
		"    same \"printed page\" as the copyright notice for easier                    ",
		"    identification within third-party archives.                                 ",
		"                                                                                ",
		" Copyright [yyyy] [name of copyright owner]                                     ",
		"                                                                                ",
#endif
		" Licensed under the Apache License, Version 2.0 (the \"License\");              ",
		" you may not use this file except in compliance with the License.               ",
		" You may obtain a copy of the License at                                        ",
		"                                                                                ",
		"     http://www.apache.org/licenses/LICENSE-2.0                                 ",
		"                                                                                ",
		" Unless required by applicable law or agreed to in writing, software            ",
		" distributed under the License is distributed on an \"AS IS\" BASIS,            ",
		" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.       ",
		" See the License for the specific language governing permissions and            ",
		" limitations under the License.                                                 "
	};
}

#endif
